# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 17:19
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_delete', models.DateTimeField(blank=True, null=True)),
                ('time_create', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(to='app_task.Tag'),
        ),
    ]
