# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0003_auto_20200811_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tags',
        ),
    ]
