# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 04:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0007_student_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_task.School'),
        ),
    ]
