# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 06:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0010_auto_20200813_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE,
                                    to='app_task.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='app_task.Tag'),
        ),
    ]
