# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 06:13
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0011_auto_20200813_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='app_task.School'),
        ),
    ]
