# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0013_auto_20200813_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(to='app_task.Tag'),
        ),
    ]
