# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0014_auto_20200813_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app_task.Tag'),
        ),
    ]
