# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 10:13
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0017_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_delete', models.DateTimeField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('url', models.ImageField(upload_to='uploads/avatar/%Y%m%d', verbose_name='\u56fe\u7247')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avatar',
                                           to='app_task.Student', verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'avatar',
                'verbose_name': '\u5934\u50cf',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_delete', models.DateTimeField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('url', models.FileField(upload_to='uploads/document/%Y%m%d', verbose_name='\u6587\u6863')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_document',
                                           to='app_task.Student', verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'document',
                'verbose_name': '\u6587\u6863',
            },
        ),
    ]
