# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 10:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0018_avatar_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_task.Student',
                                    verbose_name='\u7528\u6237'),
        ),
    ]
