# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0021_auto_20200813_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='url',
            field=models.ImageField(upload_to='avatar/%Y%m%d', verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.FileField(upload_to='document/%Y%m%d', verbose_name='\u6587\u6863'),
        ),
    ]
