# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_task', '0022_auto_20200813_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
