# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('code', models.CharField(default='', max_length=16, verbose_name='\u5206\u7c7b\u7f16\u7801')),
                ('desc', models.TextField(default='', help_text='\u7c7b\u522b\u63cf\u8ff0', verbose_name='\u7c7b\u522b\u63cf\u8ff0')),
                ('category_level', models.IntegerField(choices=[(1, '\u4e00\u7ea7\u7c7b\u76ee'), (2, '\u4e8c\u7ea7\u7c7b\u76ee'), (3, '\u4e09\u7ea7\u7c7b\u76ee')], help_text='\u5206\u7c7b\u7ea7\u522b', verbose_name='\u5206\u7c7b\u7ea7\u522b')),
                ('is_tab', models.BooleanField(default=False, help_text='\u662f\u5426\u5bfc\u822a', verbose_name='\u662f\u5426\u5bfc\u822a')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='orders.Category', verbose_name='\u7236\u7ea7\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_delete', models.DateTimeField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_delete', models.DateTimeField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=8)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('state', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
