# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_delete', models.DateTimeField(blank=True, null=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('url', models.ImageField(upload_to='avatar/%Y%m%d', verbose_name='\u6587\u4ef6\u5730\u5740')),
            ],
            options={
                'db_table': 'avatar',
                'verbose_name': '\u5934\u50cf',
            },
        ),
    ]
